### ISSUE TITLE
后台布局，让block控制还是在layout里定义好布局？

### ISSUE THREAD

**Issue by adileli** [aplisin/aplisin#5]
layout_default.html.twig 文件目前定义了sidebar和main这两个block。
目前的问题是.col-md-x这类GridClass要让各自的block来定义还是要在layout_default.html.tiwg里定义好这两种block的GridClass？
@torghay

**Comment by adileli** [comment]
让block自己定义虽然灵活，但是重写会增加工作量。

**Comment by ehmetlabs** [comment]
已做参考，GridClass在layout_default.html.tiwg里面定义了
